{% set name = "procrunner" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3626560e8ad34e4dccf2d9fca4f999242c3b875ed596c20a6c82541a6e2888de
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - procrunner

about:
  home: https://github.com/DiamondLightSource/python-procrunner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Versatile utility function to run external processes
  doc_url: https://procrunner.readthedocs.io/en/latest/
  dev_url: https://github.com/DiamondLightSource/python-procrunner

extra:
  recipe-maintainers:
    - rjgildea
    - ndevenish
    - anthchirp
